{
 "title": "v1",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vali_uid",
    "label": "Validator",
    "query": " select 'V'||uid::TEXT uid from tbl_neuron where type = 'true';"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT version FROM v_version LIMIT 50 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT created_at FROM v_version LIMIT 50 "
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT up_time FROM v_version LIMIT 50 "
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Loss Analysis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT loss_before, loss_after, window_time FROM v_validator_eval_info WHERE vali_uid = '${vali_uid}' ORDER BY window_time DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Loss Analysis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT loss_improvement, window_time FROM v_validator_eval_info WHERE vali_uid = '${vali_uid}' ORDER BY window_time DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Loss Random Analysis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT loss_random_before, loss_random_after, window_time FROM v_validator_eval_info WHERE vali_uid = '${vali_uid}' ORDER BY window_time DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Loss Random Analysis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT loss_random_improvement, window_time FROM v_validator_eval_info WHERE vali_uid = '${vali_uid}' ORDER BY window_time DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Global Step",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT window_time, global_step FROM v_window_info LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Bad peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT window_time, bad_miners_count FROM v_active_miners ORDER BY window_time DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Active peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT window_time, active_miners_count FROM v_active_miners ORDER BY window_time DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Number of gradients",
   "type": "timeseries",
   "description": "Number of gradients",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT window_time, gradients_count FROM v_gradients ORDER BY window_time DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Missing gradients peers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT window_time, diff_miners_count FROM v_active_miners ORDER BY window_time DESC LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Learning Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT window_time, learning_rate FROM v_window_info LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Evaluated UIDs",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 37 },
   "targets": [
    {
     "rawSql": "SELECT window_time, eval_uids FROM v_validator_eval_info WHERE vali_uid = '${vali_uid}' ORDER BY window_time LIMIT 5000 "
    }
   ]
  },
  {
   "title": "Metadata",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT window_number, sync_window_number, avg_window_duration, blocks_per_window, gradient_retention FROM v_overview LIMIT 50 "
    }
   ]
  },
  {
   "title": "Gathered peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT gather_miners FROM v_overview LIMIT 50 "
    }
   ]
  },
  {
   "title": "Gradients missing peers",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 46 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT diff_miners FROM v_overview LIMIT 50 "
    }
   ]
  },
  { "title": "Detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Scores",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "rawSql": "SELECT   'UID' || miner_id::TEXT miner_id, sum(score) score , window_time \r\nFROM tbl_eval_info_detail aa\r\nJOIN tbl_window_info bb ON aa.window_id = bb.id\r\nJOIN tbl_version cc ON bb.id >= cc.window_id and cc.is_running = true\r\nWHERE 'V'||aa.vali_id::TEXT = '${vali_uid}'\r\nGROUP BY window_time, miner_id  HAVING sum(score) > 0"
    }
   ]
  },
  {
   "title": "Moving avg scores",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT   'UID' || miner_id::TEXT miner_id, sum(moving_avg_score) score , window_time \r\nFROM tbl_eval_info_detail aa\r\nJOIN tbl_window_info bb ON aa.window_id = bb.id\r\nJOIN tbl_version cc ON bb.id >= cc.window_id and cc.is_running = true\r\nWHERE 'V'||aa.vali_id::TEXT = '${vali_uid}'\r\nGROUP BY window_time, miner_id HAVING sum(moving_avg_score) > 0;"
    }
   ]
  },
  {
   "title": "Current Moving avg scores",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT miner_id, moving_avg_score FROM v_eval_info_detail_current WHERE (moving_avg_score > 0 AND vali_uid = '${vali_uid}') LIMIT 500 "
    }
   ]
  },
  {
   "title": "Weights",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 84 },
   "targets": [
    {
     "rawSql": "SELECT   'UID' || miner_id::TEXT miner_id, sum(weight) score , window_time \r\nFROM tbl_eval_info_detail aa\r\nJOIN tbl_window_info bb ON aa.window_id = bb.id\r\nJOIN tbl_version cc ON bb.id >= cc.window_id and cc.is_running = true\r\nWHERE 'V'||aa.vali_id::TEXT = '${vali_uid}'\r\nGROUP BY window_time, miner_id  HAVING sum(weight) > 0;"
    }
   ]
  },
  {
   "title": "Current Weights",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "rawSql": "SELECT miner_id, weight FROM v_eval_info_detail_current WHERE (moving_avg_score > 0 AND vali_uid = '${vali_uid}') LIMIT 500 "
    }
   ]
  }
 ]
}