networks:
  test:
    driver: bridge

services:
  miner1:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-miner-M111
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: miner
      WALLET_NAME: miner
      WALLET_HOTKEY: M111
      CUDA_DEVICE: cuda:1
      NETWORK: local
      DEBUG: "true"
      WANDB_API_KEY: ${WANDB_API_KEY}
      NETUID: 2
      HOST_CUDA_VERSION: 12.6
      R2_GRADIENTS_ACCOUNT_ID: ${R2_GRADIENTS_ACCOUNT_ID}
      R2_GRADIENTS_BUCKET_NAME: ${R2_GRADIENTS_BUCKET_NAME}
      R2_GRADIENTS_READ_ACCESS_KEY_ID: ${R2_GRADIENTS_READ_ACCESS_KEY_ID}
      R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ${R2_GRADIENTS_READ_SECRET_ACCESS_KEY}
      R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ${R2_GRADIENTS_WRITE_ACCESS_KEY_ID}
      R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ${R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_ACCOUNT_ID: ${R2_DATASET_ACCOUNT_ID}
      R2_DATASET_BUCKET_NAME: ${R2_DATASET_BUCKET_NAME}
      R2_DATASET_READ_ACCESS_KEY_ID: ${R2_DATASET_READ_ACCESS_KEY_ID}
      R2_DATASET_READ_SECRET_ACCESS_KEY: ${R2_DATASET_READ_SECRET_ACCESS_KEY}
      R2_DATASET_WRITE_ACCESS_KEY_ID: ${R2_DATASET_WRITE_ACCESS_KEY_ID}
      R2_DATASET_WRITE_SECRET_ACCESS_KEY: ${R2_DATASET_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_BUCKET_LIST: ${R2_DATASET_BUCKET_LIST}
      R2_AGGREGATOR_ACCOUNT_ID: ${R2_AGGREGATOR_ACCOUNT_ID}
      R2_AGGREGATOR_BUCKET_NAME: ${R2_AGGREGATOR_BUCKET_NAME}
      R2_AGGREGATOR_READ_ACCESS_KEY_ID: ${R2_AGGREGATOR_READ_ACCESS_KEY_ID}
      R2_AGGREGATOR_READ_SECRET_ACCESS_KEY: ${R2_AGGREGATOR_READ_SECRET_ACCESS_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0", "1", "2", "3", "4", "5", "6", "7" ]
              capabilities: [ gpu ]

  miner2:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-miner-M222
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: miner
      WALLET_NAME: miner
      WALLET_HOTKEY: M222
      CUDA_DEVICE: cuda:2
      NETWORK: local
      DEBUG: "true"
      WANDB_API_KEY: ${WANDB_API_KEY}
      NETUID: 2
      HOST_CUDA_VERSION: 12.6
      R2_GRADIENTS_ACCOUNT_ID: ${R2_GRADIENTS_ACCOUNT_ID}
      R2_GRADIENTS_BUCKET_NAME: ${R2_GRADIENTS_BUCKET_NAME}
      R2_GRADIENTS_READ_ACCESS_KEY_ID: ${R2_GRADIENTS_READ_ACCESS_KEY_ID}
      R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ${R2_GRADIENTS_READ_SECRET_ACCESS_KEY}
      R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ${R2_GRADIENTS_WRITE_ACCESS_KEY_ID}
      R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ${R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_ACCOUNT_ID: ${R2_DATASET_ACCOUNT_ID}
      R2_DATASET_BUCKET_NAME: ${R2_DATASET_BUCKET_NAME}
      R2_DATASET_READ_ACCESS_KEY_ID: ${R2_DATASET_READ_ACCESS_KEY_ID}
      R2_DATASET_READ_SECRET_ACCESS_KEY: ${R2_DATASET_READ_SECRET_ACCESS_KEY}
      R2_DATASET_WRITE_ACCESS_KEY_ID: ${R2_DATASET_WRITE_ACCESS_KEY_ID}
      R2_DATASET_WRITE_SECRET_ACCESS_KEY: ${R2_DATASET_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_BUCKET_LIST: ${R2_DATASET_BUCKET_LIST}
      R2_AGGREGATOR_ACCOUNT_ID: ${R2_AGGREGATOR_ACCOUNT_ID}
      R2_AGGREGATOR_BUCKET_NAME: ${R2_AGGREGATOR_BUCKET_NAME}
      R2_AGGREGATOR_READ_ACCESS_KEY_ID: ${R2_AGGREGATOR_READ_ACCESS_KEY_ID}
      R2_AGGREGATOR_READ_SECRET_ACCESS_KEY: ${R2_AGGREGATOR_READ_SECRET_ACCESS_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0", "1", "2", "3", "4", "5", "6", "7" ]
              capabilities: [ gpu ]

  validator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-validator-V11
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: validator
      WALLET_NAME: validator
      WALLET_HOTKEY: V11
      CUDA_DEVICE: cuda:3
      NETWORK: local
      DEBUG: "true"
      WANDB_API_KEY: ${WANDB_API_KEY}
      NETUID: 2
      HOST_CUDA_VERSION: 12.6
      R2_GRADIENTS_ACCOUNT_ID: ${R2_GRADIENTS_ACCOUNT_ID}
      R2_GRADIENTS_BUCKET_NAME: ${R2_GRADIENTS_BUCKET_NAME}
      R2_GRADIENTS_READ_ACCESS_KEY_ID: ${R2_GRADIENTS_READ_ACCESS_KEY_ID}
      R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ${R2_GRADIENTS_READ_SECRET_ACCESS_KEY}
      R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ${R2_GRADIENTS_WRITE_ACCESS_KEY_ID}
      R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ${R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_ACCOUNT_ID: ${R2_DATASET_ACCOUNT_ID}
      R2_DATASET_BUCKET_NAME: ${R2_DATASET_BUCKET_NAME}
      R2_DATASET_READ_ACCESS_KEY_ID: ${R2_DATASET_READ_ACCESS_KEY_ID}
      R2_DATASET_READ_SECRET_ACCESS_KEY: ${R2_DATASET_READ_SECRET_ACCESS_KEY}
      R2_DATASET_WRITE_ACCESS_KEY_ID: ${R2_DATASET_WRITE_ACCESS_KEY_ID}
      R2_DATASET_WRITE_SECRET_ACCESS_KEY: ${R2_DATASET_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_BUCKET_LIST: ${R2_DATASET_BUCKET_LIST}
      R2_AGGREGATOR_ACCOUNT_ID: ${R2_AGGREGATOR_ACCOUNT_ID}
      R2_AGGREGATOR_BUCKET_NAME: ${R2_AGGREGATOR_BUCKET_NAME}
      R2_AGGREGATOR_READ_ACCESS_KEY_ID: ${R2_AGGREGATOR_READ_ACCESS_KEY_ID}
      R2_AGGREGATOR_READ_SECRET_ACCESS_KEY: ${R2_AGGREGATOR_READ_SECRET_ACCESS_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0", "1", "2", "3", "4", "5", "6", "7" ]
              capabilities: [ gpu ]

  aggregator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-aggregator-A11
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: aggregator
      WALLET_NAME: aggregator
      WALLET_HOTKEY: A11
      CUDA_DEVICE: cuda:5
      NETWORK: local
      DEBUG: "true"
      WANDB_API_KEY: ${WANDB_API_KEY}
      NETUID: 2
      R2_GRADIENTS_ACCOUNT_ID: ${R2_GRADIENTS_ACCOUNT_ID}
      R2_GRADIENTS_BUCKET_NAME: ${R2_GRADIENTS_BUCKET_NAME}
      R2_GRADIENTS_READ_ACCESS_KEY_ID: ${R2_GRADIENTS_READ_ACCESS_KEY_ID}
      R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ${R2_GRADIENTS_READ_SECRET_ACCESS_KEY}
      R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ${R2_GRADIENTS_WRITE_ACCESS_KEY_ID}
      R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ${R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_ACCOUNT_ID: ${R2_DATASET_ACCOUNT_ID}
      R2_DATASET_BUCKET_NAME: ${R2_DATASET_BUCKET_NAME}
      R2_DATASET_READ_ACCESS_KEY_ID: ${R2_DATASET_READ_ACCESS_KEY_ID}
      R2_DATASET_READ_SECRET_ACCESS_KEY: ${R2_DATASET_READ_SECRET_ACCESS_KEY}
      R2_DATASET_WRITE_ACCESS_KEY_ID: ${R2_DATASET_WRITE_ACCESS_KEY_ID}
      R2_DATASET_WRITE_SECRET_ACCESS_KEY: ${R2_DATASET_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_BUCKET_LIST: ${R2_DATASET_BUCKET_LIST}
      R2_AGGREGATOR_ACCOUNT_ID: ${R2_AGGREGATOR_ACCOUNT_ID}
      R2_AGGREGATOR_BUCKET_NAME: ${R2_AGGREGATOR_BUCKET_NAME}
      R2_AGGREGATOR_READ_ACCESS_KEY_ID: ${R2_AGGREGATOR_READ_ACCESS_KEY_ID}
      R2_AGGREGATOR_READ_SECRET_ACCESS_KEY: ${R2_AGGREGATOR_READ_SECRET_ACCESS_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0", "1", "2", "3", "4", "5", "6", "7" ]
              capabilities: [ gpu ]

  evaluator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: templar-evaluator-E11
    networks:
      - test
    volumes:
      - ~/.bittensor/wallets:/root/.bittensor/wallets
      - ../logs:/app/logs
    environment:
      NODE_TYPE: evaluator
      WALLET_NAME: evaluator
      WALLET_HOTKEY: E11
      CUDA_DEVICE: cuda:6
      NETWORK: local
      DEBUG: "true"
      WANDB_API_KEY: ${WANDB_API_KEY}
      NETUID: 2
      R2_GRADIENTS_ACCOUNT_ID: ${R2_GRADIENTS_ACCOUNT_ID}
      R2_GRADIENTS_BUCKET_NAME: ${R2_GRADIENTS_BUCKET_NAME}
      R2_GRADIENTS_READ_ACCESS_KEY_ID: ${R2_GRADIENTS_READ_ACCESS_KEY_ID}
      R2_GRADIENTS_READ_SECRET_ACCESS_KEY: ${R2_GRADIENTS_READ_SECRET_ACCESS_KEY}
      R2_GRADIENTS_WRITE_ACCESS_KEY_ID: ${R2_GRADIENTS_WRITE_ACCESS_KEY_ID}
      R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY: ${R2_GRADIENTS_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_ACCOUNT_ID: ${R2_DATASET_ACCOUNT_ID}
      R2_DATASET_BUCKET_NAME: ${R2_DATASET_BUCKET_NAME}
      R2_DATASET_READ_ACCESS_KEY_ID: ${R2_DATASET_READ_ACCESS_KEY_ID}
      R2_DATASET_READ_SECRET_ACCESS_KEY: ${R2_DATASET_READ_SECRET_ACCESS_KEY}
      R2_DATASET_WRITE_ACCESS_KEY_ID: ${R2_DATASET_WRITE_ACCESS_KEY_ID}
      R2_DATASET_WRITE_SECRET_ACCESS_KEY: ${R2_DATASET_WRITE_SECRET_ACCESS_KEY}
      R2_DATASET_BUCKET_LIST: ${R2_DATASET_BUCKET_LIST}
      R2_AGGREGATOR_ACCOUNT_ID: ${R2_AGGREGATOR_ACCOUNT_ID}
      R2_AGGREGATOR_BUCKET_NAME: ${R2_AGGREGATOR_BUCKET_NAME}
      R2_AGGREGATOR_READ_ACCESS_KEY_ID: ${R2_AGGREGATOR_READ_ACCESS_KEY_ID}
      R2_AGGREGATOR_READ_SECRET_ACCESS_KEY: ${R2_AGGREGATOR_READ_SECRET_ACCESS_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0", "1", "2", "3", "4", "5", "6", "7" ]
              capabilities: [ gpu ]
