---
- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: reload systemctl
  systemd:
    daemon_reload: yes
