{
 "title": "Eval - Metrics",
 "tags": [ "evals" ],
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Eval - hellaswag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"tplr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Ebenchmark_metrics\" or r[\"_measurement\"] == \"Ebenchmark_task\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"role\"] == \"evaluator\")\r\n  |> filter(fn: (r) => r[\"task\"] == \"hellaswag\")\r\n  |> group(columns: [\"version\", \"uid\", \"task\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Eval - mmlu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"tplr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Ebenchmark_metrics\" or r[\"_measurement\"] == \"Ebenchmark_task\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"role\"] == \"evaluator\")\r\n  |> filter(fn: (r) => r[\"task\"] == \"mmlu\")\r\n  |> group(columns: [\"version\", \"uid\", \"task\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Eval - piqa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"tplr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Ebenchmark_metrics\" or r[\"_measurement\"] == \"Ebenchmark_task\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"role\"] == \"evaluator\")\r\n  |> filter(fn: (r) => r[\"task\"] == \"piqa\")\r\n  |> group(columns: [\"version\", \"uid\", \"task\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Eval - arc_challenge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"tplr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Ebenchmark_metrics\" or r[\"_measurement\"] == \"Ebenchmark_task\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"role\"] == \"evaluator\")\r\n  |> filter(fn: (r) => r[\"task\"] == \"arc_challenge\")\r\n  |> group(columns: [\"version\", \"uid\", \"task\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Eval - arc_easy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"tplr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Ebenchmark_metrics\" or r[\"_measurement\"] == \"Ebenchmark_task\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"role\"] == \"evaluator\")\r\n  |> filter(fn: (r) => r[\"task\"] == \"arc_easy\")\r\n  |> group(columns: [\"version\", \"uid\", \"task\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Eval - openbookqa",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"tplr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Ebenchmark_metrics\" or r[\"_measurement\"] == \"Ebenchmark_task\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"role\"] == \"evaluator\")\r\n  |> filter(fn: (r) => r[\"task\"] == \"openbookqa\")\r\n  |> group(columns: [\"version\", \"uid\", \"task\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Eval - winogrande",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "query": "from(bucket: \"tplr\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Ebenchmark_metrics\" or r[\"_measurement\"] == \"Ebenchmark_task\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"score\")\r\n  |> filter(fn: (r) => r[\"role\"] == \"evaluator\")\r\n  |> filter(fn: (r) => r[\"task\"] == \"winogrande\")\r\n  |> group(columns: [\"version\", \"uid\", \"task\"], mode:\"by\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}