"""Initial migration

Revision ID: 073c51e8625a
Revises: 
Create Date: 2025-01-27 19:25:20.375234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '073c51e8625a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_neuron',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=100), nullable=False),
    sa.Column('hotkey', sa.String(length=100), nullable=False),
    sa.Column('coldkey', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    op.create_table('tbl_run_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('avg_window_duration', sa.Float(), nullable=True),
    sa.Column('gradient_retention', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_window_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_number', sa.Integer(), nullable=False),
    sa.Column('window_time', sa.DateTime(), nullable=False),
    sa.Column('global_step', sa.Integer(), nullable=False),
    sa.Column('learning_rate', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_active_miners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('active_miners', sa.PickleType(), nullable=False),
    sa.ForeignKeyConstraint(['window_id'], ['tbl_window_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_eval_info_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('vali_id', sa.Integer(), nullable=False),
    sa.Column('miner_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('moving_avg_score', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['miner_id'], ['tbl_neuron.id'], ),
    sa.ForeignKeyConstraint(['vali_id'], ['tbl_neuron.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['tbl_window_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_gradients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('neuron_id', sa.Integer(), nullable=False),
    sa.Column('r2_bucketname', sa.String(length=200), nullable=False),
    sa.Column('gradient_filename', sa.String(length=200), nullable=False),
    sa.Column('gradient_filesize', sa.Float(), nullable=False),
    sa.Column('gradient_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['neuron_id'], ['tbl_neuron.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['tbl_window_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_neuron_third_party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neuron_id', sa.Integer(), nullable=False),
    sa.Column('r2_bucket_name', sa.String(length=200), nullable=False),
    sa.Column('r2_read_access_key_id', sa.String(length=200), nullable=False),
    sa.Column('r2_read_secrect_access_key', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['neuron_id'], ['tbl_neuron.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_validator_eval_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('neuron_id', sa.Integer(), nullable=False),
    sa.Column('loss_before', sa.Float(), nullable=True),
    sa.Column('loss_after', sa.Float(), nullable=True),
    sa.Column('loss_improvement', sa.Float(), nullable=True),
    sa.Column('current_eval_uid', sa.String(length=200), nullable=True),
    sa.Column('eval_uids', sa.PickleType(), nullable=True),
    sa.Column('mean_scores', sa.Float(), nullable=True),
    sa.Column('mean_moving_avg_scores', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['neuron_id'], ['tbl_neuron.id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['tbl_window_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_validator_eval_info')
    op.drop_table('tbl_neuron_third_party')
    op.drop_table('tbl_gradients')
    op.drop_table('tbl_eval_info_detail')
    op.drop_table('tbl_active_miners')
    op.drop_table('tbl_window_info')
    op.drop_table('tbl_version')
    op.drop_table('tbl_run_metadata')
    op.drop_table('tbl_neuron')
    # ### end Alembic commands ###
