"""Update tbl_active_miners

Revision ID: 1290073edfe1
Revises: 6291b2aebfda
Create Date: 2025-02-08 15:38:33.625277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1290073edfe1'
down_revision = '6291b2aebfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_active_miners', sa.Column('bad_miners', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_active_miners', 'bad_miners')
    # ### end Alembic commands ###
