"""Update FK for tbl_neuron

Revision ID: 35d84a91cbf7
Revises: 7d8568fc8b9e
Create Date: 2025-02-10 13:36:59.524922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35d84a91cbf7'
down_revision = '7d8568fc8b9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tbl_eval_info_detail_vali_id_fkey', 'tbl_eval_info_detail', type_='foreignkey')
    op.drop_constraint('tbl_eval_info_detail_miner_id_fkey', 'tbl_eval_info_detail', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_eval_info_detail', 'tbl_neuron', ['vali_id'], ['uid'])
    op.create_foreign_key(None, 'tbl_eval_info_detail', 'tbl_neuron', ['miner_id'], ['uid'])
    op.drop_constraint('tbl_gradients_neuron_id_fkey', 'tbl_gradients', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_gradients', 'tbl_neuron', ['neuron_id'], ['uid'])
    op.drop_constraint('tbl_neuron_third_party_neuron_id_fkey', 'tbl_neuron_third_party', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_neuron_third_party', 'tbl_neuron', ['neuron_id'], ['uid'])
    op.drop_constraint('tbl_validator_eval_info_neuron_id_fkey', 'tbl_validator_eval_info', type_='foreignkey')
    op.create_foreign_key(None, 'tbl_validator_eval_info', 'tbl_neuron', ['neuron_id'], ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tbl_validator_eval_info', type_='foreignkey')
    op.create_foreign_key('tbl_validator_eval_info_neuron_id_fkey', 'tbl_validator_eval_info', 'tbl_neuron', ['neuron_id'], ['id'])
    op.drop_constraint(None, 'tbl_neuron_third_party', type_='foreignkey')
    op.create_foreign_key('tbl_neuron_third_party_neuron_id_fkey', 'tbl_neuron_third_party', 'tbl_neuron', ['neuron_id'], ['id'])
    op.drop_constraint(None, 'tbl_gradients', type_='foreignkey')
    op.create_foreign_key('tbl_gradients_neuron_id_fkey', 'tbl_gradients', 'tbl_neuron', ['neuron_id'], ['id'])
    op.drop_constraint(None, 'tbl_eval_info_detail', type_='foreignkey')
    op.drop_constraint(None, 'tbl_eval_info_detail', type_='foreignkey')
    op.create_foreign_key('tbl_eval_info_detail_miner_id_fkey', 'tbl_eval_info_detail', 'tbl_neuron', ['miner_id'], ['id'])
    op.create_foreign_key('tbl_eval_info_detail_vali_id_fkey', 'tbl_eval_info_detail', 'tbl_neuron', ['vali_id'], ['id'])
    # ### end Alembic commands ###
