"""Update tbl_window_info table

Revision ID: 42f0cf61d90d
Revises: 8d6ac055a52d
Create Date: 2025-02-11 03:19:08.879729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f0cf61d90d'
down_revision = '8d6ac055a52d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_window_info', sa.Column('sync_window_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_window_info', 'sync_window_number')
    # ### end Alembic commands ###
