"""Update tbl_active_miners

Revision ID: 7d8568fc8b9e
Revises: 91e59a6fe8f6
Create Date: 2025-02-10 12:44:27.824472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d8568fc8b9e'
down_revision = '91e59a6fe8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_active_miners', sa.Column('gather_miners', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_active_miners', 'gather_miners')
    # ### end Alembic commands ###
