"""Update tbl_run_metadata

Revision ID: 91e59a6fe8f6
Revises: 1290073edfe1
Create Date: 2025-02-08 15:51:38.324992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e59a6fe8f6'
down_revision = '1290073edfe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_run_metadata', sa.Column('blocks_per_window', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_run_metadata', 'blocks_per_window')
    # ### end Alembic commands ###
