"""Update tbl_active_miners table

Revision ID: e668ceabdeaa
Revises: 42f0cf61d90d
Create Date: 2025-02-11 07:31:22.652601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e668ceabdeaa'
down_revision = '42f0cf61d90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_active_miners', sa.Column('diff_miners', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_active_miners', 'diff_miners')
    # ### end Alembic commands ###
