"""Update tbl_window_info table

Revision ID: ef4d4293e780
Revises: e668ceabdeaa
Create Date: 2025-02-11 09:12:06.408856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef4d4293e780'
down_revision = 'e668ceabdeaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_version', sa.Column('window_id', sa.Integer(), nullable=True))
    op.drop_column('tbl_version', 'window_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_version', sa.Column('window_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('tbl_version', 'window_id')
    # ### end Alembic commands ###
